/**
 * Matmul Test Harness
 * 
 * This file provides the main() entry point and test infrastructure
 * for verifying matmul kernels on RISC-V with RVV.
 * 
 * Compile with: -DMATRIX_SIZE=64 (or 128, 256)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifndef MATRIX_SIZE
#define MATRIX_SIZE 64
#endif

#define N MATRIX_SIZE

// External kernel function (generated by KernelSmith)
extern void matmul_NxN(float* C, const float* A, const float* B);

// Reference implementation
void matmul_ref(float* C, const float* A, const float* B, int n) {
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            float sum = 0.0f;
            for (int k = 0; k < n; k++) {
                sum += A[i * n + k] * B[k * n + j];
            }
            C[i * n + j] = sum;
        }
    }
}

// Initialize matrix with predictable values
void init_matrix(float* M, int n, int seed) {
    for (int i = 0; i < n * n; i++) {
        // Simple PRNG for reproducibility
        seed = (seed * 1103515245 + 12345) & 0x7fffffff;
        M[i] = (float)(seed % 1000) / 1000.0f - 0.5f;
    }
}

// Compare matrices
int compare_matrices(const float* C1, const float* C2, int n, float tol) {
    int errors = 0;
    float max_diff = 0.0f;
    
    for (int i = 0; i < n * n; i++) {
        float diff = fabsf(C1[i] - C2[i]);
        if (diff > max_diff) max_diff = diff;
        if (diff > tol) {
            if (errors < 10) {
                printf("Mismatch at [%d]: got %f, expected %f (diff=%f)\n",
                       i, C1[i], C2[i], diff);
            }
            errors++;
        }
    }
    
    printf("Max difference: %e\n", max_diff);
    return errors;
}

int main() {
    printf("Matmul Test: %dx%d\n", N, N);
    
    // Allocate matrices
    float* A = (float*)aligned_alloc(64, N * N * sizeof(float));
    float* B = (float*)aligned_alloc(64, N * N * sizeof(float));
    float* C = (float*)aligned_alloc(64, N * N * sizeof(float));
    float* C_ref = (float*)aligned_alloc(64, N * N * sizeof(float));
    
    if (!A || !B || !C || !C_ref) {
        printf("ERROR: Memory allocation failed\n");
        return 1;
    }
    
    // Initialize
    init_matrix(A, N, 42);
    init_matrix(B, N, 123);
    memset(C, 0, N * N * sizeof(float));
    memset(C_ref, 0, N * N * sizeof(float));
    
    // Compute reference
    printf("Computing reference...\n");
    matmul_ref(C_ref, A, B, N);
    
    // Run generated kernel
    printf("Running generated kernel...\n");
    matmul_NxN(C, A, B);
    
    // Compare
    printf("Comparing results...\n");
    int errors = compare_matrices(C, C_ref, N, 1e-4f);
    
    // Cleanup
    free(A);
    free(B);
    free(C);
    free(C_ref);
    
    if (errors == 0) {
        printf("PASS: Results match\n");
        return 0;
    } else {
        printf("FAIL: %d mismatches\n", errors);
        return 1;
    }
}
